---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
spec:
  description: {{ .Release.Description }}
  imageName: {{ .Values.image.name}}:{{ .Values.image.tag }}
  instances: {{ .Values.instances }}
  bootstrap:
    initdb: #  Setup the database.
      database: {{ .Values.database.name }}
      owner: {{ .Values.database.owner }}
      secret:
        name: {{ .Values.dbName }}-owner-user
  storage:
    {{- toYaml .Values.storage | nindent 4 }}
  walStorage:
    {{- toYaml .Values.walStorage | nindent 4 }}

  resources:
    {{- toYaml .Values.resources | nindent 4 }}

  postgresql:
    parameters:
      {{- toYaml .Values.pgParameters | nindent  6 }}
